const games = [
  {
    _id: "game-wuthering-waves",
    slug: "wuthering-waves",
    name: "鸣潮",
    subtitle: "公测开荒 / 声骸全配 / 角色推荐",
    coverImage: "",
    themeColor: "#1c7f8a",
    keywords: ["鸣潮", "声骸", "开荒", "角色"],
    status: "published",
    sortOrder: 1
  },
  {
    _id: "game-stardew-valley",
    slug: "stardew-valley",
    name: "星露谷物语",
    subtitle: "作物收益 / 村民好感 / 四季钓鱼",
    coverImage: "",
    themeColor: "#d6863c",
    keywords: ["星露谷", "作物", "送礼", "钓鱼"],
    status: "published",
    sortOrder: 2
  },
  {
    _id: "game-rock-kingdom",
    slug: "rock-kingdom",
    name: "洛克王国",
    subtitle: "宠物图鉴 / 经典练级 / BOSS打法",
    coverImage: "",
    themeColor: "#6f66d8",
    keywords: ["洛克王国", "宠物", "练级", "天梯"],
    status: "published",
    sortOrder: 3
  }
];

const categories = [
  { _id: "cat-ww-character-index", gameSlug: "wuthering-waves", name: "角色图鉴", description: "共鸣者定位 / 技能 / 培养优先级", icon: "角", status: "published", sortOrder: 1 },
  { _id: "cat-ww-weapon-index", gameSlug: "wuthering-waves", name: "武器图鉴", description: "武器属性 / 适配角色 / 抽取建议", icon: "武", status: "published", sortOrder: 2 },
  { _id: "cat-ww-echo-index", gameSlug: "wuthering-waves", name: "声骸图鉴", description: "声骸套装 / 主词条 / 获取位置", icon: "声", status: "published", sortOrder: 3 },
  { _id: "cat-ww-character-stats", gameSlug: "wuthering-waves", name: "角色属性", description: "基础面板 / 突破材料 / 技能倍率", icon: "属", status: "published", sortOrder: 4 },
  { _id: "cat-ww-gacha-plan", gameSlug: "wuthering-waves", name: "抽卡规划", description: "卡池节奏 / 星声预算 / 补强路线", icon: "抽", status: "published", sortOrder: 5 },
  { _id: "cat-ww-build-stats", gameSlug: "wuthering-waves", name: "角色配装统计", description: "武器声骸使用率 / 队伍搭配统计", icon: "配", status: "published", sortOrder: 6 },
  { _id: "cat-sv-crop", gameSlug: "stardew-valley", name: "四季作物", description: "作物收益及成熟时间", icon: "作", status: "published", sortOrder: 1 },
  { _id: "cat-sv-gift", gameSlug: "stardew-valley", name: "村民好感", description: "全 NPC 最爱 / 喜欢礼物", icon: "礼", status: "published", sortOrder: 2 },
  { _id: "cat-sv-tool", gameSlug: "stardew-valley", name: "日常工具", description: "钓鱼时间表 / 矿洞攻略", icon: "工", status: "published", sortOrder: 3 },
  { _id: "cat-rk-egg-size", gameSlug: "rock-kingdom", name: "蛋尺寸查询", description: "宠物蛋尺寸 / 孵化信息 / 查询索引", icon: "蛋", status: "published", sortOrder: 1 },
  { _id: "cat-rk-egg-group-pair", gameSlug: "rock-kingdom", name: "蛋组配对", description: "蛋组关系 / 可配对精灵 / 遗传路线", icon: "组", status: "published", sortOrder: 2 },
  { _id: "cat-rk-pvp-damage", gameSlug: "rock-kingdom", name: "PVP属性伤害计算", description: "属性克制 / 伤害倍率 / 对战计算", icon: "伤", status: "published", sortOrder: 3 },
  { _id: "cat-rk-skill-pet-filter", gameSlug: "rock-kingdom", name: "技能筛选精灵", description: "按技能反查精灵 / 技能持有者", icon: "筛", status: "published", sortOrder: 4 },
  { _id: "cat-rk-pet-list", gameSlug: "rock-kingdom", name: "精灵列表", description: "精灵基础资料 / 属性 / 编号索引", icon: "灵", status: "published", sortOrder: 5 },
  { _id: "cat-rk-skill-list", gameSlug: "rock-kingdom", name: "技能列表", description: "技能属性 / 威力 / 效果说明", icon: "技", status: "published", sortOrder: 6 },
  { _id: "cat-rk-team-list", gameSlug: "rock-kingdom", name: "阵容列表", description: "PVP 阵容 / 副本阵容 / 搭配思路", icon: "阵", status: "published", sortOrder: 7 },
  { _id: "cat-rk-item-index", gameSlug: "rock-kingdom", name: "道具图鉴", description: "道具用途 / 获取方式 / 消耗场景", icon: "具", status: "published", sortOrder: 8 },
  { _id: "cat-rk-counter-table", gameSlug: "rock-kingdom", name: "克制关系表", description: "属性克制 / 抵抗 / 免疫速查", icon: "克", status: "published", sortOrder: 9 },
  { _id: "cat-rk-nature-traits", gameSlug: "rock-kingdom", name: "性格特点", description: "性格加成 / 推荐方向 / 培养建议", icon: "性", status: "published", sortOrder: 10 },
  { _id: "cat-rk-skill-terms", gameSlug: "rock-kingdom", name: "技能词条", description: "技能效果词条 / 状态解释 / 机制说明", icon: "词", status: "published", sortOrder: 11 }
];

const articles = [
  {
    _id: "article-ww-character-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-character-index",
    title: "鸣潮角色图鉴速查",
    summary: "按属性、定位和队伍功能整理共鸣者，方便快速判断培养优先级。",
    tags: ["角色图鉴", "共鸣者", "定位"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>角色图鉴使用方式</h2><p>先按属性和定位筛选角色，再查看核心技能、队伍职责和培养优先级。</p><h3>建议字段</h3><ul><li>属性、武器类型、定位、稀有度。</li><li>核心技能、共鸣链关键节点、适配队友。</li><li>培养优先级和适用场景。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3280,
    favoriteCount: 248,
    shareCount: 76,
    status: "published",
    sortOrder: 1
  },
  {
    _id: "article-ww-weapon-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-weapon-index",
    title: "鸣潮武器图鉴与适配角色",
    summary: "整理常用武器属性、特效、适配角色和抽取建议。",
    tags: ["武器图鉴", "适配角色", "抽取建议"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>武器图鉴结构</h2><p>每把武器建议记录基础攻击、主属性、武器特效和推荐角色。</p><h3>抽取判断</h3><ul><li>先看是否绑定核心主 C。</li><li>再看同类替代武器差距。</li><li>最后结合当前星声预算决定。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2190,
    favoriteCount: 133,
    shareCount: 42,
    status: "published",
    sortOrder: 2
  },
  {
    _id: "article-ww-echo-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-echo-index",
    title: "鸣潮声骸图鉴与套装速查",
    summary: "整理声骸套装、主词条选择、COST 搭配和获取位置。",
    tags: ["声骸图鉴", "套装", "主词条"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>声骸图鉴结构</h2><p>按套装、COST、主词条和适配角色整理声骸，方便玩家快速查配装。</p><h3>常用信息</h3><ul><li>套装效果和推荐角色。</li><li>主词条、副词条优先级。</li><li>获取区域和刷取建议。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 1460,
    favoriteCount: 88,
    shareCount: 25,
    status: "published",
    sortOrder: 3
  },
  {
    _id: "article-ww-character-stats",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-character-stats",
    title: "鸣潮角色属性与突破材料表",
    summary: "集中展示角色基础属性、突破材料、技能升级材料和关键倍率。",
    tags: ["角色属性", "突破材料", "技能倍率"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>角色属性表</h2><p>这里适合放每个角色的等级面板、突破加成、技能倍率和材料消耗。</p><h3>建议字段</h3><ul><li>生命、攻击、防御、暴击、暴伤。</li><li>突破材料和周本材料。</li><li>技能升级优先级和倍率变化。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1260,
    favoriteCount: 76,
    shareCount: 18,
    status: "published",
    sortOrder: 4
  },
  {
    _id: "article-ww-gacha-plan",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-gacha-plan",
    title: "鸣潮抽卡规划与星声预算",
    summary: "按版本卡池、角色定位和账号缺口整理抽卡优先级。",
    tags: ["抽卡规划", "星声", "卡池"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>抽卡规划思路</h2><p>先确认当前账号缺主 C、辅助还是生存位，再结合版本卡池和星声预算决定。</p><h3>规划步骤</h3><ol><li>记录当前角色池和武器池。</li><li>判断未来两个版本的补强目标。</li><li>预留保底所需星声，避免冲动抽卡。</li></ol>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1880,
    favoriteCount: 142,
    shareCount: 39,
    status: "published",
    sortOrder: 5
  },
  {
    _id: "article-ww-build-stats",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-build-stats",
    title: "鸣潮角色配装统计速览",
    summary: "统计热门角色的武器、声骸、词条和队伍搭配使用率。",
    tags: ["角色配装统计", "武器使用率", "声骸搭配"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>配装统计看什么</h2><p>配装统计用于快速了解当前主流搭配，但最终仍要结合自己的词条质量。</p><h3>统计维度</h3><ul><li>武器使用率和替代方案。</li><li>声骸套装、COST 和主词条占比。</li><li>常见队伍搭配和循环手法。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1640,
    favoriteCount: 118,
    shareCount: 31,
    status: "published",
    sortOrder: 6
  },
  {
    _id: "article-4",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-crop",
    title: "四季作物收益速查",
    summary: "春夏秋冬高收益作物、成熟时间和复种建议。",
    tags: ["作物", "收益", "四季"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>作物速查</h2><p>春季优先草莓，夏季优先蓝莓和杨桃，秋季优先蔓越莓。</p><p>真实上线时可以替换成完整收益表。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 4230,
    favoriteCount: 362,
    shareCount: 96,
    status: "published",
    sortOrder: 4
  },
  {
    _id: "article-5",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-gift",
    title: "全村民送礼好感表",
    summary: "每位 NPC 的最爱、喜欢、生日和避雷礼物。",
    tags: ["送礼", "好感", "NPC"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>送礼原则</h2><p>生日当天送最爱礼物收益最高，平时优先准备容易量产的喜欢礼物。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3988,
    favoriteCount: 420,
    shareCount: 101,
    status: "published",
    sortOrder: 5
  },
  {
    _id: "article-6",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-tool",
    title: "钓鱼时间与矿洞 120 层路线",
    summary: "按季节、天气、时间整理鱼类与矿洞推进策略。",
    tags: ["钓鱼", "矿洞", "日常"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>日常工具</h2><p>钓鱼看季节、天气、时间和地点；矿洞建议带足食物和楼梯。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2012,
    favoriteCount: 176,
    shareCount: 55,
    status: "published",
    sortOrder: 6
  },
  {
    _id: "article-rk-egg-size",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-egg-size",
    title: "洛克王国蛋尺寸查询表",
    summary: "按宠物蛋尺寸、孵化信息和对应宠物整理查询索引。",
    tags: ["蛋尺寸查询", "宠物蛋", "孵化"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>蛋尺寸查询</h2><p>这里用于整理不同宠物蛋的尺寸、来源、孵化时间和对应宠物。</p><h3>建议字段</h3><ul><li>蛋名称、尺寸、蛋组。</li><li>可孵化宠物和获取方式。</li><li>是否适合遗传或收藏。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 2880,
    favoriteCount: 238,
    shareCount: 81,
    status: "published",
    sortOrder: 7
  },
  {
    _id: "article-rk-egg-group-pair",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-egg-group-pair",
    title: "洛克王国蛋组配对速查",
    summary: "整理蛋组关系、可配对精灵和遗传技能路线。",
    tags: ["蛋组配对", "遗传", "精灵"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>蛋组配对</h2><p>按蛋组查询可配对精灵，帮助玩家规划遗传技能和繁育路线。</p><h3>建议字段</h3><ul><li>父母精灵、蛋组、可遗传技能。</li><li>配对条件和限制。</li><li>推荐遗传路线。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 1712,
    favoriteCount: 120,
    shareCount: 33,
    status: "published",
    sortOrder: 8
  },
  {
    _id: "article-rk-pvp-damage",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pvp-damage",
    title: "PVP 属性伤害计算入门",
    summary: "按属性克制、技能类型和对战场景整理伤害计算思路。",
    tags: ["PVP属性伤害计算", "属性克制", "伤害倍率"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>PVP 伤害计算</h2><p>这里适合放属性倍率、技能威力、增伤减伤和实战计算案例。</p><h3>计算维度</h3><ul><li>攻击方属性、技能属性和威力。</li><li>防守方属性、抗性和减伤。</li><li>天气、强化、装备和状态影响。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 2566,
    favoriteCount: 211,
    shareCount: 68,
    status: "published",
    sortOrder: 9
  },
  {
    _id: "article-rk-skill-pet-filter",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-skill-pet-filter",
    title: "按技能筛选精灵查询",
    summary: "输入技能名后反查可学习或携带该技能的精灵。",
    tags: ["技能筛选精灵", "技能反查", "精灵"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>技能反查精灵</h2><p>这里用于整理技能和精灵的对应关系，方便按技能找可用宠物。</p><h3>建议字段</h3><ul><li>技能名称、属性、效果。</li><li>可学习精灵和获取方式。</li><li>是否可遗传、是否限定。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1540,
    favoriteCount: 126,
    shareCount: 30,
    status: "published",
    sortOrder: 10
  },
  {
    _id: "article-rk-pet-list",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pet-list",
    title: "洛克王国精灵列表",
    summary: "整理精灵编号、属性、种族值、获取方式和推荐用途。",
    tags: ["精灵列表", "宠物", "种族值"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>精灵列表</h2><p>每只精灵建议记录编号、属性、种族值、获取方式和适用场景。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 2860,
    favoriteCount: 230,
    shareCount: 74,
    status: "published",
    sortOrder: 11
  },
  {
    _id: "article-rk-skill-list",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-skill-list",
    title: "洛克王国技能列表",
    summary: "按技能属性、威力、命中、PP 和效果整理技能图鉴。",
    tags: ["技能列表", "技能属性", "效果"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>技能列表</h2><p>这里适合放技能名称、属性、威力、命中、PP、效果和可学习精灵。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1980,
    favoriteCount: 166,
    shareCount: 42,
    status: "published",
    sortOrder: 12
  },
  {
    _id: "article-rk-team-list",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-team-list",
    title: "洛克王国阵容列表",
    summary: "整理 PVP、天梯、副本和活动常用阵容搭配。",
    tags: ["阵容列表", "PVP", "副本"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>阵容列表</h2><p>按使用场景整理阵容，包括核心精灵、替补位、技能顺序和克制关系。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1760,
    favoriteCount: 148,
    shareCount: 39,
    status: "published",
    sortOrder: 13
  },
  {
    _id: "article-rk-item-index",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-item-index",
    title: "洛克王国道具图鉴",
    summary: "整理道具用途、获取方式、消耗场景和优先级。",
    tags: ["道具图鉴", "获取方式", "消耗"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>道具图鉴</h2><p>这里用于记录培养材料、活动道具、消耗品和关键兑换物。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1420,
    favoriteCount: 102,
    shareCount: 28,
    status: "published",
    sortOrder: 14
  },
  {
    _id: "article-rk-counter-table",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-counter-table",
    title: "洛克王国克制关系表",
    summary: "快速查询属性之间的克制、抵抗和弱点关系。",
    tags: ["克制关系表", "属性", "弱点"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>克制关系表</h2><p>这里适合放属性克制矩阵，帮助玩家快速判断技能和阵容克制。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 2210,
    favoriteCount: 196,
    shareCount: 61,
    status: "published",
    sortOrder: 15
  },
  {
    _id: "article-rk-nature-traits",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-nature-traits",
    title: "洛克王国性格特点速查",
    summary: "整理不同性格的属性倾向、推荐精灵和培养方向。",
    tags: ["性格特点", "性格", "培养"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>性格特点</h2><p>这里用于说明性格对精灵培养方向的影响，并给出常见推荐。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1680,
    favoriteCount: 138,
    shareCount: 36,
    status: "published",
    sortOrder: 16
  },
  {
    _id: "article-rk-skill-terms",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-skill-terms",
    title: "洛克王国技能词条解释",
    summary: "解释技能描述中的常见状态、机制词条和触发条件。",
    tags: ["技能词条", "状态", "机制"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>技能词条</h2><p>把技能描述里的强化、弱化、异常、先手、免疫等词条整理成可查字典。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1320,
    favoriteCount: 98,
    shareCount: 24,
    status: "published",
    sortOrder: 17
  }
];

const admins = [
  { _id: "admin-mock", openid: "mock-admin-openid", name: "本地管理员" }
];

module.exports = {
  games,
  categories,
  articles,
  admins
};
