const games = [
  {
    _id: "game-wuthering-waves",
    slug: "wuthering-waves",
    name: "鸣潮",
    subtitle: "公测开荒 / 声骸全配 / 角色推荐",
    coverImage: "",
    themeColor: "#1c7f8a",
    keywords: ["鸣潮", "声骸", "开荒", "角色"],
    status: "published",
    sortOrder: 1
  },
  {
    _id: "game-stardew-valley",
    slug: "stardew-valley",
    name: "星露谷物语",
    subtitle: "作物收益 / 村民好感 / 四季钓鱼",
    coverImage: "",
    themeColor: "#d6863c",
    keywords: ["星露谷", "作物", "送礼", "钓鱼"],
    status: "published",
    sortOrder: 2
  },
  {
    _id: "game-rock-kingdom",
    slug: "rock-kingdom",
    name: "洛克王国",
    subtitle: "宠物图鉴 / 经典练级 / BOSS打法",
    coverImage: "",
    themeColor: "#6f66d8",
    keywords: ["洛克王国", "宠物", "练级", "天梯"],
    status: "published",
    sortOrder: 3
  }
];

const categories = [
  { _id: "cat-ww-character-index", gameSlug: "wuthering-waves", name: "角色图鉴", description: "共鸣者定位 / 技能 / 培养优先级", icon: "角", status: "published", sortOrder: 1 },
  { _id: "cat-ww-weapon-index", gameSlug: "wuthering-waves", name: "武器图鉴", description: "武器属性 / 适配角色 / 抽取建议", icon: "武", status: "published", sortOrder: 2 },
  { _id: "cat-ww-echo-index", gameSlug: "wuthering-waves", name: "声骸图鉴", description: "声骸套装 / 主词条 / 获取位置", icon: "声", status: "published", sortOrder: 3 },
  { _id: "cat-ww-character-stats", gameSlug: "wuthering-waves", name: "角色属性", description: "基础面板 / 突破材料 / 技能倍率", icon: "属", status: "published", sortOrder: 4 },
  { _id: "cat-ww-gacha-plan", gameSlug: "wuthering-waves", name: "抽卡规划", description: "卡池节奏 / 星声预算 / 补强路线", icon: "抽", status: "published", sortOrder: 5 },
  { _id: "cat-ww-build-stats", gameSlug: "wuthering-waves", name: "角色配装统计", description: "武器声骸使用率 / 队伍搭配统计", icon: "配", status: "published", sortOrder: 6 },
  { _id: "cat-sv-crop", gameSlug: "stardew-valley", name: "四季作物", description: "作物收益及成熟时间", icon: "作", status: "published", sortOrder: 1 },
  { _id: "cat-sv-gift", gameSlug: "stardew-valley", name: "村民好感", description: "全 NPC 最爱 / 喜欢礼物", icon: "礼", status: "published", sortOrder: 2 },
  { _id: "cat-sv-tool", gameSlug: "stardew-valley", name: "日常工具", description: "钓鱼时间表 / 矿洞攻略", icon: "工", status: "published", sortOrder: 3 },
  { _id: "cat-rk-pet", gameSlug: "rock-kingdom", name: "神宠图鉴", description: "种族值 / 性格 / 技能石", icon: "宠", status: "published", sortOrder: 1 },
  { _id: "cat-rk-pve", gameSlug: "rock-kingdom", name: "天梯/副本", description: "PK 阵容 / BOSS 打法", icon: "战", status: "published", sortOrder: 2 },
  { _id: "cat-rk-level", gameSlug: "rock-kingdom", name: "怀旧练级", description: "1-100 级快速升级路线", icon: "级", status: "published", sortOrder: 3 }
];

const articles = [
  {
    _id: "article-ww-character-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-character-index",
    title: "鸣潮角色图鉴速查",
    summary: "按属性、定位和队伍功能整理共鸣者，方便快速判断培养优先级。",
    tags: ["角色图鉴", "共鸣者", "定位"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>角色图鉴使用方式</h2><p>先按属性和定位筛选角色，再查看核心技能、队伍职责和培养优先级。</p><h3>建议字段</h3><ul><li>属性、武器类型、定位、稀有度。</li><li>核心技能、共鸣链关键节点、适配队友。</li><li>培养优先级和适用场景。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3280,
    favoriteCount: 248,
    shareCount: 76,
    status: "published",
    sortOrder: 1
  },
  {
    _id: "article-ww-weapon-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-weapon-index",
    title: "鸣潮武器图鉴与适配角色",
    summary: "整理常用武器属性、特效、适配角色和抽取建议。",
    tags: ["武器图鉴", "适配角色", "抽取建议"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>武器图鉴结构</h2><p>每把武器建议记录基础攻击、主属性、武器特效和推荐角色。</p><h3>抽取判断</h3><ul><li>先看是否绑定核心主 C。</li><li>再看同类替代武器差距。</li><li>最后结合当前星声预算决定。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2190,
    favoriteCount: 133,
    shareCount: 42,
    status: "published",
    sortOrder: 2
  },
  {
    _id: "article-ww-echo-index",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-echo-index",
    title: "鸣潮声骸图鉴与套装速查",
    summary: "整理声骸套装、主词条选择、COST 搭配和获取位置。",
    tags: ["声骸图鉴", "套装", "主词条"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>声骸图鉴结构</h2><p>按套装、COST、主词条和适配角色整理声骸，方便玩家快速查配装。</p><h3>常用信息</h3><ul><li>套装效果和推荐角色。</li><li>主词条、副词条优先级。</li><li>获取区域和刷取建议。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 1460,
    favoriteCount: 88,
    shareCount: 25,
    status: "published",
    sortOrder: 3
  },
  {
    _id: "article-ww-character-stats",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-character-stats",
    title: "鸣潮角色属性与突破材料表",
    summary: "集中展示角色基础属性、突破材料、技能升级材料和关键倍率。",
    tags: ["角色属性", "突破材料", "技能倍率"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>角色属性表</h2><p>这里适合放每个角色的等级面板、突破加成、技能倍率和材料消耗。</p><h3>建议字段</h3><ul><li>生命、攻击、防御、暴击、暴伤。</li><li>突破材料和周本材料。</li><li>技能升级优先级和倍率变化。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1260,
    favoriteCount: 76,
    shareCount: 18,
    status: "published",
    sortOrder: 4
  },
  {
    _id: "article-ww-gacha-plan",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-gacha-plan",
    title: "鸣潮抽卡规划与星声预算",
    summary: "按版本卡池、角色定位和账号缺口整理抽卡优先级。",
    tags: ["抽卡规划", "星声", "卡池"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>抽卡规划思路</h2><p>先确认当前账号缺主 C、辅助还是生存位，再结合版本卡池和星声预算决定。</p><h3>规划步骤</h3><ol><li>记录当前角色池和武器池。</li><li>判断未来两个版本的补强目标。</li><li>预留保底所需星声，避免冲动抽卡。</li></ol>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1880,
    favoriteCount: 142,
    shareCount: 39,
    status: "published",
    sortOrder: 5
  },
  {
    _id: "article-ww-build-stats",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-build-stats",
    title: "鸣潮角色配装统计速览",
    summary: "统计热门角色的武器、声骸、词条和队伍搭配使用率。",
    tags: ["角色配装统计", "武器使用率", "声骸搭配"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>配装统计看什么</h2><p>配装统计用于快速了解当前主流搭配，但最终仍要结合自己的词条质量。</p><h3>统计维度</h3><ul><li>武器使用率和替代方案。</li><li>声骸套装、COST 和主词条占比。</li><li>常见队伍搭配和循环手法。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 1640,
    favoriteCount: 118,
    shareCount: 31,
    status: "published",
    sortOrder: 6
  },
  {
    _id: "article-4",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-crop",
    title: "四季作物收益速查",
    summary: "春夏秋冬高收益作物、成熟时间和复种建议。",
    tags: ["作物", "收益", "四季"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>作物速查</h2><p>春季优先草莓，夏季优先蓝莓和杨桃，秋季优先蔓越莓。</p><p>真实上线时可以替换成完整收益表。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 4230,
    favoriteCount: 362,
    shareCount: 96,
    status: "published",
    sortOrder: 4
  },
  {
    _id: "article-5",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-gift",
    title: "全村民送礼好感表",
    summary: "每位 NPC 的最爱、喜欢、生日和避雷礼物。",
    tags: ["送礼", "好感", "NPC"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>送礼原则</h2><p>生日当天送最爱礼物收益最高，平时优先准备容易量产的喜欢礼物。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3988,
    favoriteCount: 420,
    shareCount: 101,
    status: "published",
    sortOrder: 5
  },
  {
    _id: "article-6",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-tool",
    title: "钓鱼时间与矿洞 120 层路线",
    summary: "按季节、天气、时间整理鱼类与矿洞推进策略。",
    tags: ["钓鱼", "矿洞", "日常"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>日常工具</h2><p>钓鱼看季节、天气、时间和地点；矿洞建议带足食物和楼梯。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2012,
    favoriteCount: 176,
    shareCount: 55,
    status: "published",
    sortOrder: 6
  },
  {
    _id: "article-7",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pet",
    title: "热门神宠性格与技能搭配",
    summary: "热门宠物种族值、推荐性格和技能石搭配占位。",
    tags: ["神宠", "性格", "技能"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>神宠图鉴</h2><p>每只宠物建议包含种族值、推荐性格、核心技能和获取方式。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 2880,
    favoriteCount: 238,
    shareCount: 81,
    status: "published",
    sortOrder: 7
  },
  {
    _id: "article-8",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pve",
    title: "天梯阵容与 BOSS 打法",
    summary: "当前版本主流阵容、克制思路和副本 Boss 处理方式。",
    tags: ["天梯", "副本", "BOSS"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>打法结构</h2><p>首版可以按 BOSS 名称、推荐宠物、技能顺序和翻车点整理。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 1712,
    favoriteCount: 120,
    shareCount: 33,
    status: "published",
    sortOrder: 8
  },
  {
    _id: "article-9",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-level",
    title: "1-100 级怀旧练级路线",
    summary: "从低级场景到高经验副本的练级路线和注意事项。",
    tags: ["练级", "路线", "怀旧"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>练级路线</h2><p>按等级段拆分场景和推荐怪物，方便玩家打开就查。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 2566,
    favoriteCount: 211,
    shareCount: 68,
    status: "published",
    sortOrder: 9
  }
];

const admins = [
  { _id: "admin-mock", openid: "mock-admin-openid", name: "本地管理员" }
];

module.exports = {
  games,
  categories,
  articles,
  admins
};
