const games = [
  {
    _id: "game-wuthering-waves",
    slug: "wuthering-waves",
    name: "鸣潮",
    subtitle: "公测开荒 / 声骸全配 / 角色推荐",
    coverImage: "",
    themeColor: "#1c7f8a",
    keywords: ["鸣潮", "声骸", "开荒", "角色"],
    status: "published",
    sortOrder: 1
  },
  {
    _id: "game-stardew-valley",
    slug: "stardew-valley",
    name: "星露谷物语",
    subtitle: "作物收益 / 村民好感 / 四季钓鱼",
    coverImage: "",
    themeColor: "#d6863c",
    keywords: ["星露谷", "作物", "送礼", "钓鱼"],
    status: "published",
    sortOrder: 2
  },
  {
    _id: "game-rock-kingdom",
    slug: "rock-kingdom",
    name: "洛克王国",
    subtitle: "宠物图鉴 / 经典练级 / BOSS打法",
    coverImage: "",
    themeColor: "#6f66d8",
    keywords: ["洛克王国", "宠物", "练级", "天梯"],
    status: "published",
    sortOrder: 3
  }
];

const categories = [
  { _id: "cat-ww-build", gameSlug: "wuthering-waves", name: "角色养成", description: "全角色武器 / 声骸搭配列表", icon: "声", status: "published", sortOrder: 1 },
  { _id: "cat-ww-starter", gameSlug: "wuthering-waves", name: "开荒必备", description: "主线流程 / 解密 / 声骸路线", icon: "荒", status: "published", sortOrder: 2 },
  { _id: "cat-ww-data", gameSlug: "wuthering-waves", name: "数据图鉴", description: "武器属性 / 材料掉落表", icon: "数", status: "published", sortOrder: 3 },
  { _id: "cat-sv-crop", gameSlug: "stardew-valley", name: "四季作物", description: "作物收益及成熟时间", icon: "作", status: "published", sortOrder: 1 },
  { _id: "cat-sv-gift", gameSlug: "stardew-valley", name: "村民好感", description: "全 NPC 最爱 / 喜欢礼物", icon: "礼", status: "published", sortOrder: 2 },
  { _id: "cat-sv-tool", gameSlug: "stardew-valley", name: "日常工具", description: "钓鱼时间表 / 矿洞攻略", icon: "工", status: "published", sortOrder: 3 },
  { _id: "cat-rk-pet", gameSlug: "rock-kingdom", name: "神宠图鉴", description: "种族值 / 性格 / 技能石", icon: "宠", status: "published", sortOrder: 1 },
  { _id: "cat-rk-pve", gameSlug: "rock-kingdom", name: "天梯/副本", description: "PK 阵容 / BOSS 打法", icon: "战", status: "published", sortOrder: 2 },
  { _id: "cat-rk-level", gameSlug: "rock-kingdom", name: "怀旧练级", description: "1-100 级快速升级路线", icon: "级", status: "published", sortOrder: 3 }
];

const articles = [
  {
    _id: "article-1",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-build",
    title: "全角色声骸与武器搭配速查",
    summary: "先用一篇表格式攻略跑通鸣潮角色养成查询体验。",
    tags: ["声骸", "武器", "角色"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>推荐查询方式</h2><p>先选角色定位，再看武器、声骸主词条和副词条优先级。</p><h3>示例结论</h3><ul><li>主 C 优先保证暴击、攻击和属性伤害。</li><li>辅助优先看充能、治疗或增伤能力。</li><li>后续可把整理好的长图放到图鉴预览区。</li></ul>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3280,
    favoriteCount: 248,
    shareCount: 76,
    status: "published",
    sortOrder: 1
  },
  {
    _id: "article-2",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-starter",
    title: "新手开荒每日路线",
    summary: "主线推进、体力消耗、声骸收集和地图解密的首周路线。",
    tags: ["开荒", "每日", "路线"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>首周优先级</h2><p>主线优先，体力别溢出，声骸先凑套装再追毕业词条。</p><ol><li>完成主线和每日任务。</li><li>清掉明显能拿的地图资源。</li><li>需要卡等级时再刷材料和声骸。</li></ol>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2190,
    favoriteCount: 133,
    shareCount: 42,
    status: "published",
    sortOrder: 2
  },
  {
    _id: "article-3",
    gameSlug: "wuthering-waves",
    gameName: "鸣潮",
    categoryId: "cat-ww-data",
    title: "武器与突破材料掉落表",
    summary: "用于承接后续材料表格、长图和掉落地点整理。",
    tags: ["材料", "武器", "掉落"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>材料表占位</h2><p>这里适合放武器材料、角色突破材料、周本材料的速查表。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 1460,
    favoriteCount: 88,
    shareCount: 25,
    status: "published",
    sortOrder: 3
  },
  {
    _id: "article-4",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-crop",
    title: "四季作物收益速查",
    summary: "春夏秋冬高收益作物、成熟时间和复种建议。",
    tags: ["作物", "收益", "四季"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>作物速查</h2><p>春季优先草莓，夏季优先蓝莓和杨桃，秋季优先蔓越莓。</p><p>真实上线时可以替换成完整收益表。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 4230,
    favoriteCount: 362,
    shareCount: 96,
    status: "published",
    sortOrder: 4
  },
  {
    _id: "article-5",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-gift",
    title: "全村民送礼好感表",
    summary: "每位 NPC 的最爱、喜欢、生日和避雷礼物。",
    tags: ["送礼", "好感", "NPC"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>送礼原则</h2><p>生日当天送最爱礼物收益最高，平时优先准备容易量产的喜欢礼物。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 3988,
    favoriteCount: 420,
    shareCount: 101,
    status: "published",
    sortOrder: 5
  },
  {
    _id: "article-6",
    gameSlug: "stardew-valley",
    gameName: "星露谷物语",
    categoryId: "cat-sv-tool",
    title: "钓鱼时间与矿洞 120 层路线",
    summary: "按季节、天气、时间整理鱼类与矿洞推进策略。",
    tags: ["钓鱼", "矿洞", "日常"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>日常工具</h2><p>钓鱼看季节、天气、时间和地点；矿洞建议带足食物和楼梯。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 2012,
    favoriteCount: 176,
    shareCount: 55,
    status: "published",
    sortOrder: 6
  },
  {
    _id: "article-7",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pet",
    title: "热门神宠性格与技能搭配",
    summary: "热门宠物种族值、推荐性格和技能石搭配占位。",
    tags: ["神宠", "性格", "技能"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>神宠图鉴</h2><p>每只宠物建议包含种族值、推荐性格、核心技能和获取方式。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-18",
    viewCount: 2880,
    favoriteCount: 238,
    shareCount: 81,
    status: "published",
    sortOrder: 7
  },
  {
    _id: "article-8",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-pve",
    title: "天梯阵容与 BOSS 打法",
    summary: "当前版本主流阵容、克制思路和副本 Boss 处理方式。",
    tags: ["天梯", "副本", "BOSS"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>打法结构</h2><p>首版可以按 BOSS 名称、推荐宠物、技能顺序和翻车点整理。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-17",
    viewCount: 1712,
    favoriteCount: 120,
    shareCount: 33,
    status: "published",
    sortOrder: 8
  },
  {
    _id: "article-9",
    gameSlug: "rock-kingdom",
    gameName: "洛克王国",
    categoryId: "cat-rk-level",
    title: "1-100 级怀旧练级路线",
    summary: "从低级场景到高经验副本的练级路线和注意事项。",
    tags: ["练级", "路线", "怀旧"],
    coverImage: "",
    imageUrls: [],
    contentHtml: "<h2>练级路线</h2><p>按等级段拆分场景和推荐怪物，方便玩家打开就查。</p>",
    authorNote: "本文整理自网络，侵删",
    publishedAt: "2026-05-16",
    createdAt: "2026-05-16",
    updatedAt: "2026-05-16",
    viewCount: 2566,
    favoriteCount: 211,
    shareCount: 68,
    status: "published",
    sortOrder: 9
  }
];

const admins = [
  { _id: "admin-mock", openid: "mock-admin-openid", name: "本地管理员" }
];

module.exports = {
  games,
  categories,
  articles,
  admins
};
